dependencies:
  - name: mongodb
    alias: REPLACE_ME_APP_NAME-db # will be replace with the name of the application when the build pack is applied
    version: 5.3.0
    repository:  https://kubernetes-charts.storage.googleapis.com
    condition: db.enabled